export const coworkersData = [
    {
        id: 1,
        name: 'Ana Silva',
        area: 'Web Developer',
        linkedin: 'https://www.linkedin.com/in/anasilva/',
        portfolio: 'https://www.anasilvaportfolio.com/',
        linkImg: 'https://example.com/anasilva.jpg',
        description: 'Desenvolvedora web com experiência em front-end e back-end.',
    },
    {
        id: 2,
        name: 'John Doe',
        area: 'Graphic Designer',
        linkedin: 'https://www.linkedin.com/in/johndoe/',
        portfolio: 'https://www.johndoeprojects.com/',
        linkImg: 'https://example.com/johndoe.jpg',
        description: 'Designer gráfico com foco em design visualmente atraente.',
    },
    {
        id: 3,
        name: 'Maria Garcia',
        area: 'Software Engineer',
        linkedin: 'https://www.linkedin.com/in/mariagarcia/',
        portfolio: 'https://www.mariagarcia.dev/',
        linkImg: 'https://example.com/mariagarcia.jpg',
        description: 'Engenheira de software especializada em desenvolvimento de aplicativos.',
    },
    {
        id: 4,
        name: 'David Smith',
        area: 'UX Designer',
        linkedin: 'https://www.linkedin.com/in/davidsmith/',
        portfolio: 'https://www.davidsmithdesigns.com/',
        linkImg: 'https://example.com/davidsmith.jpg',
        description: 'Designer de experiência do usuário (UX) com foco em interfaces intuitivas.',
    },
    {
        id: 5,
        name: 'Sophie Johnson',
        area: 'Content Writer',
        linkedin: 'https://www.linkedin.com/in/sophiejohnson/',
        portfolio: 'https://www.sophiecontent.com/',
        linkImg: 'https://example.com/sophiejohnson.jpg',
        description: 'Redatora de conteúdo criativo e persuasivo.',
    },
    {
        id: 6,
        name: 'Carlos Rodriguez',
        area: 'Marketing Specialist',
        linkedin: 'https://www.linkedin.com/in/carlosrodriguez/',
        portfolio: 'https://www.carlosmarketingworks.com/',
        linkImg: 'https://example.com/carlosrodriguez.jpg',
        description: 'Especialista em marketing com experiência em estratégias de divulgação.',
    },
    {
        id: 7,
        name: 'Linda Chang',
        area: 'Data Analyst',
        linkedin: 'https://www.linkedin.com/in/lindachang/',
        portfolio: 'https://www.lindadataanalysis.com/',
        linkImg: 'https://example.com/lindachang.jpg',
        description: 'Analista de dados experiente em análise e interpretação de dados.',
    },
    {
        id: 8,
        name: 'Paulo Oliveira',
        area: 'Mobile App Developer',
        linkedin: 'https://www.linkedin.com/in/paulooliveira/',
        portfolio: 'https://www.pauloappportfolio.com/',
        linkImg: 'https://example.com/paulooliveira.jpg',
        description: 'Desenvolvedor de aplicativos móveis com conhecimento em desenvolvimento mobile.',
    },
    {
        id: 9,
        name: 'Emily Anderson',
        area: 'Illustrator',
        linkedin: 'https://www.linkedin.com/in/emilyanderson/',
        portfolio: 'https://www.emilyillustrations.com/',
        linkImg: 'https://example.com/emilyanderson.jpg',
        description: 'Ilustradora talentosa com habilidades criativas em desenho e pintura digital.',
    },
    {
        id: 10,
        name: 'Robert Taylor',
        area: 'SEO Specialist',
        linkedin: 'https://www.linkedin.com/in/roberttaylor/',
        portfolio: 'https://www.robertseoworks.com/',
        linkImg: 'https://example.com/roberttaylor.jpg',
        description: 'Especialista em SEO (Otimização de Mecanismos de Busca) focado em melhorar a visibilidade online.',
    },


];